# ====================== Site Settings ======================
url: https://support.naluscientific.com
title: Nalu Scientific Support
description: Support website for Nalu Scientific products.

# ====================== Plugin Settings ======================
plugins:
  - jekyll-include-cache
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# ====================== Theme Settings ======================
logo: /assets/images/masthead.png
masthead_title: "Nalu Scientific Support"
minimal_mistakes_skin: air

# ====================== Default Styles ======================
# These are defaults used for the frontmatter for these file types
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false


# ====================== Exclude From Processing ======================
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"
  - README.md
  - staticman.yml
  - Rakefile
  - "*LICENSE"


# ====================== Miscellaneous ======================
# required by github pages
github: [metadata]
