name: Build Board Documentation

on:
  workflow_dispatch:


jobs:
  run_build:
    name: Run Board Documentation Build Script
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Run Script
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
          python board_docs.py --inid ${{ variables.DRIVE_BOARD_DOCS_INPUT_FOLDER }} --outid ${{ variables.DRIVE_BOARD_DOCS_OUTPUT_FOLDER }} --credentials ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }} --driveid ${{ variables.DRIVE_ID }}
